- name: "Installing all python libraries in the node"
  hosts: localhost
  connection: local
  roles:
    - ebs
    - efs
    - nlb
  vars:
    account: "exampleaccountID"
    k8s_cluster_name: "clustername"
    region: eu-north-1
    k8s_role: quix-eks-node-group-example #this is iam_role_name from node managed
    k8s_id: 3FDFA841example
    k8s_key_id: fed8e2fa-example
    efs_id: fs-example
  
